import {ICar} from '../models/types';

export const cars: ICar[] = [
  {
    id: 0,
    model: 'Genesis G70',
    subscriptionTillDate: '2022-07-14',
    licensePlateNumber: 'K 332 MB 777',
    street: 'ул. Рубинштейна',
    house: '22к4',
    currency: '₽',
    services: [
      {
        id: 0,
        title: 'Заправить',
        subTitle: 'АИ-95',
        serviceType: 'fuel',
        price: '3325',
        priceComment: '~45 мин',
        amountOfFuel: 20,
      },
      {
        id: 1,
        title: 'Техобслуживание',
        serviceType: 'maintenance',
        price: '27200',
        items: ['Масло ДВС', 'фильтры'],
        priceComment: '~6 ч',
      },
      {
        id: 2,
        title: 'Штрафы',
        subTitle: '4 новых',
        serviceType: 'fines',
        price: '5200',
        priceComment: 'Всего',
      },
      {
        id: 3,
        title: 'Паркинг',
        subTitle: '№ 1119',
        serviceType: 'parking',
        price: '800',
        priceComment: 'Всего',
      },
      {
        id: 4,
        title: 'АЗС',
        subTitle: '1.6 км',
        serviceType: 'gasStation',
        price: '49',
        priceComment: '1л АИ-95',
      },
    ],
  },
  {
    id: 1,
    model: 'Nissan Skyline R34',
    subscriptionTillDate: '2022-10-11',
    licensePlateNumber: 'K 456 MB 123',
    street: 'ул. Рубинштейна',
    house: '22к4',
    currency: '₽',
    services: [
      {
        id: 0,
        title: 'Заправить',
        subTitle: 'АИ-95',
        serviceType: 'fuel',
        price: '1234',
        priceComment: '~34 мин',
        amountOfFuel: 20,
      },
      {
        id: 1,
        title: 'Техобслуживание',
        serviceType: 'maintenance',
        price: '55666',
        items: ['Гидравлический фазоинвертор', 'циклический прото-излучатель'],
        priceComment: '~6 ч',
      },
      {
        id: 2,
        title: 'Штрафы',
        subTitle: '4 новых',
        serviceType: 'fines',
        price: '5200',
        priceComment: 'Всего',
      },
      {
        id: 3,
        title: 'Паркинг',
        subTitle: '№ 1119',
        serviceType: 'parking',
        price: '800',
        priceComment: 'Всего',
      },
      {
        id: 4,
        title: 'АЗС',
        subTitle: '№ 555',
        serviceType: 'gasStation',
        price: '49',
        priceComment: '1л АИ-95',
      },
    ],
  },
];
